enum SessionDeliveryDetailsQuestions {
  SESSION_FREQUENCY = 'SESSION_FREQUENCY',
  SESSION_DELIVERY_METHOD = 'SESSION_DELIVERY_METHOD',
  SESSION_FORMAT = 'SESSION_FORMAT',
  RISK_ASSOCIATED_WITH_PLANNED_ACTIVITIES = 'RISK_ASSOCIATED_WITH_PLANNED_ACTIVITIES',
  REASONABLE_ADJUSTMENTS_FOR_PLANNED_ACTIVITIES = 'REASONABLE_ADJUSTMENTS_FOR_PLANNED_ACTIVITIES',
  SERVICE_END_DATE_CHECK = 'SERVICE_END_DATE_CHECK',
}

export default SessionDeliveryDetailsQuestions
