/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/referral/{referralId}/assign': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Assign case workers to a referral */
    post: operations['assignCaseWorkers']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/{referralId}/submit-a-referral': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit a referral */
    post: operations['submitReferral']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a referral */
    post: operations['createReferral']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral/{referralId}/ics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get all ICS appointments for a referral */
    get: operations['getIcsAppointments']
    put?: never
    /** Book an ICS appointment for a referral */
    post: operations['createIcsAppointment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral/{referralId}/ics/{icsId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a single ICS appointment by ID */
    get: operations['getIcsAppointment']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-select-a-service': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get community support services for referral select-a-service */
    get: operations['getServices']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-details/{referralId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a referral by ID */
    get: operations['getReferral']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-details/{referralId}/progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get referral progress page data */
    get: operations['getReferralProgressDetails']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-details-page/{caseIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get referral details page data */
    get: operations['getReferralDetailsPage']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-assignments/{referralId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get assigned case workers of a referral */
    get: operations['getAssignedCaseWorkers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/reference-data/probation-offices': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get list of probation offices */
    get: operations['getProbationOffices']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/person/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Find a person by an identifier i.e Prison Number or CRN */
    get: operations['getPersonDetails']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/case-list/unassigned': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get unassigned referrals for a community service provider */
    get: operations['getUnassignedCases']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/case-list/in-progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get in-progress referrals for a community service provider */
    get: operations['getInProgressCases']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AssignCaseWorkersRequest: {
      emails: string[]
    }
    AssignCaseWorkersResult: {
      success: boolean
      message: string
      succeededList?: components['schemas']['CaseWorkerDto'][]
      failureList?: components['schemas']['AssignmentFailureDto'][]
    }
    AssignmentFailureDto: {
      emailAddress: string
      reason: string
    }
    CaseWorkerDto: {
      /** @enum {string} */
      userType: 'INTERNAL' | 'EXTERNAL'
      /** Format: uuid */
      userId?: string
      fullName?: string
      emailAddress: string
    }
    SubmitReferralResponseDto: {
      /** Format: uuid */
      referralId: string
      referenceNumber?: string
    }
    CreateReferralRequest: {
      personDetails: components['schemas']['PersonDto']
      /** Format: uuid */
      communityServiceProviderId: string
      crn: string
      urgency?: boolean
    }
    PersonAdditionalDetails: {
      ethnicity?: string
      preferredLanguage?: string
      neurodiverseConditions?: string
      religionOrBelief?: string
      transgender?: string
      sexualOrientation?: string
      address?: string
      phoneNumber?: string
      emailAddress?: string
    }
    PersonDto: {
      /** Format: uuid */
      id: string
      personIdentifier?: string
      firstName: string
      lastName: string
      /** Format: date */
      dateOfBirth: string
      sex?: string
      additionalDetails?: components['schemas']['PersonAdditionalDetails']
    }
    ReferralInformationDto: {
      /** Format: uuid */
      personId: string
      /** Format: uuid */
      referralId: string
      firstName?: string
      lastName?: string
      sex?: string
      crn: string
      /** Format: uuid */
      communityServiceProviderId: string
      communityServiceProviderName: string
      region: string
      referenceNumber?: string
      deliveryPartner: string
    }
    AppointmentTimeRequest: {
      /** Format: int32 */
      hour: number
      /** Format: int32 */
      minute?: number
      amPm: string
    }
    CreateAppointmentRequest: {
      /** Format: date */
      date: string
      time: components['schemas']['AppointmentTimeRequest']
      sessionMethodRequest: components['schemas']['SessionMethodRequest']
      sessionCommunication: string[]
    }
    SessionMethodRequest: {
      /** @enum {string} */
      type: 'PHONE' | 'VIDEO' | 'PROBATION_OFFICE' | 'OTHER_LOCATION'
      additionalDetails?: string
      addressLine1?: string
      addressLine2?: string
      townOrCity?: string
      county?: string
      postcode?: string
    }
    AppointmentIcsResponse: {
      /** Format: uuid */
      appointmentIcsId: string
      /** Format: uuid */
      appointmentId: string
      /** Format: uuid */
      referralId: string
      /** @enum {string} */
      appointmentType: 'ICS'
      /** Format: date */
      appointmentDate: string
      appointmentTime: components['schemas']['AppointmentTimeResponse']
      /** @enum {string} */
      appointmentStatus: 'SCHEDULED' | 'NEEDS_FEEDBACK' | 'COMPLETED' | 'RESCHEDULED' | 'DID_NOT_ATTEND'
      sessionMethod: components['schemas']['SessionMethod']
      sessionCommunications: string[]
      referralFirstName: string
      referralLastName: string
      /** Format: date-time */
      createdAt: string
    }
    AppointmentTimeResponse: {
      /** Format: int32 */
      hour: number
      /** Format: int32 */
      minute: number
      amPm: string
    }
    InPersonAppointment: Omit<WithRequired<components['schemas']['SessionMethod'], 'type'>, 'appointmentCategory'> & {
      probationOfficeName?: string
      addressLine1?: string
      addressLine2?: string
      townOrCity?: string
      county?: string
      postcode?: string
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      appointmentCategory: 'IN_PERSON'
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      appointmentCategory: 'IN_PERSON'
    }
    SessionMethod: {
      type: string
      appointmentCategory: string
    } & (components['schemas']['VirtualAppointment'] | components['schemas']['InPersonAppointment'])
    VirtualAppointment: Omit<WithRequired<components['schemas']['SessionMethod'], 'type'>, 'appointmentCategory'> & {
      whyNotInPersonReason?: string
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      appointmentCategory: 'VIRTUAL'
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      appointmentCategory: 'VIRTUAL'
    }
    CommunitySupportServiceDto: {
      id: string
      region: string
      name: string
      providerName: string
      description: string
    }
    CommunitySupportServicesDto: {
      personId: string
      communitySupportServices: components['schemas']['CommunitySupportServiceDto'][]
    }
    ErrorResponse: {
      /**
       * Format: int32
       * @description The HTTP status code returned by the server
       * @example 404
       */
      status: number
      /**
       * Format: int32
       * @description An application-specific error code
       * @example 404
       */
      errorCode?: number
      /**
       * @description A human readable message for the error
       * @example Referral Not found
       */
      userMessage?: string
      /**
       * @description A developer friendly message for the error
       * @example null
       */
      developerMessage?: string
      /**
       * @description Additional information about the error
       * @example null
       */
      moreInfo?: string
    }
    ContactDetailsTableDataDto: {
      phoneNumber?: string
      mobileNumber?: string
      email?: string
      address?: string
    }
    EqualityDetailsTableDataDto: {
      ethnicity?: string
      religionOrBelief?: string
      sex: string
      genderIdentity: string
      sexualOrientation: string
      transgender: string
    }
    PersonDetailsTableDataDto: {
      name: string
      crn: string
      dateOfBirth: string
      preferredLanguage: string
      disabilities: string
    }
    ReferralDetailsBffResponseDto: {
      /** Format: uuid */
      id: string
      referenceNumber?: string
      /** Format: date-time */
      createdDate: string
      personDetailsTableData: components['schemas']['PersonDetailsTableDataDto']
      equalityDetailsTableData: components['schemas']['EqualityDetailsTableDataDto']
      contactDetailsTableData: components['schemas']['ContactDetailsTableDataDto']
      referralDetailsTableData: components['schemas']['ReferralDetailsTableDataDto']
    }
    ReferralDetailsTableDataDto: {
      referralDate: string
      assignedTo: string[]
    }
    ReferralAppointmentHistoryDto: {
      /** Format: uuid */
      appointmentId: string
      /** @enum {string} */
      type: 'ICS'
      /** Format: date-time */
      dateTime: string
      /** @enum {string} */
      status: 'SCHEDULED' | 'NEEDS_FEEDBACK' | 'COMPLETED' | 'RESCHEDULED' | 'DID_NOT_ATTEND'
    }
    ReferralProgressDto: {
      /** Format: uuid */
      referralId: string
      fullName: string
      appointments: components['schemas']['ReferralAppointmentHistoryDto'][]
    }
    ProbationOffice: {
      /** Format: int32 */
      probationOfficeId: number
      name: string
      address: string
      probationRegionId: string
      govUkUrl?: string
      deliusCRSLocationId?: string
    }
    Pageable: {
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      sort?: string[]
    }
    ReferralCaseListDto: {
      /** Format: uuid */
      referralId: string
      referenceNumber: string
      personName: string
      personIdentifier: string
      date: string
      caseWorkers: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  assignCaseWorkers: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AssignCaseWorkersRequest']
      }
    }
    responses: {
      /** @description Assign case workers to a referral */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AssignCaseWorkersResult']
        }
      }
      /** @description Failed to assign case worker(s) */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AssignCaseWorkersResult']
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  submitReferral: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SubmitReferralResponseDto']
        }
      }
    }
  }
  createReferral: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateReferralRequest']
      }
    }
    responses: {
      /** @description Referral created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralInformationDto']
        }
      }
    }
  }
  getIcsAppointments: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of ICS appointments */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AppointmentIcsResponse'][]
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  createIcsAppointment: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAppointmentRequest']
      }
    }
    responses: {
      /** @description Appointment created successfully */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AppointmentIcsResponse']
        }
      }
      /** @description Invalid request body */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getIcsAppointment: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
        icsId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description ICS appointment found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AppointmentIcsResponse']
        }
      }
      /** @description Appointment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getServices: {
    parameters: {
      query: {
        personDetailsId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of community support services */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CommunitySupportServicesDto']
        }
      }
      /** @description The request was unauthorised */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden. The client is not authorised to access to select a referral service. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getReferral: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralDetailsBffResponseDto']
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getReferralProgressDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral progress details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralProgressDto'][]
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getReferralDetailsPage: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral Details found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralDetailsBffResponseDto']
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getAssignedCaseWorkers: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Assignments found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseWorkerDto'][]
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getProbationOffices: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Returns the list of Probation Offices Information. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProbationOffice'][]
        }
      }
      /** @description Failed to retrieve Probation Offices Information */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getPersonDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Person found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PersonDto']
        }
      }
      /** @description Person not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getUnassignedCases: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of unassigned referrals for the provider */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralCaseListDto'][]
        }
      }
      /** @description The request was unauthorised */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden. The client is not authorised to access the case list. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getInProgressCases: {
    parameters: {
      query: {
        pageable: components['schemas']['Pageable']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of in-progress referrals for the provider */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralCaseListDto'][]
        }
      }
      /** @description The request was unauthorised */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden. The client is not authorised to access the case list. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getReferralInformation: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral Details found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralInformationDto']
        }
      }
      /** @description The request was unauthorised */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden. The client is not authorised to access the case list. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
type WithRequired<T, K extends keyof T> = T & {
  [P in K]-?: T[P]
}
