/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/bff/{referralId}/submit-a-referral': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit a referral */
    post: operations['submitReferral']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a referral */
    post: operations['createReferral']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-select-a-service': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get community support services for referral select-a-service */
    get: operations['getServices']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/referral-details/{referralId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a referral by ID */
    get: operations['getReferral']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/bff/person/{personIdentifier}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Find a person by an identifier i.e Prison Number or CRN */
    get: operations['getPersonDetails']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    SubmitReferralResponseDto: {
      /** Format: uuid */
      referralId: string
      referenceNumber?: string
    }
    CreateReferralRequest: {
      /** Format: uuid */
      personId: string
      /** Format: uuid */
      communityServiceProviderId: string
      crn: string
      urgency?: boolean
    }
    ReferralInformationDto: {
      /** Format: uuid */
      personId: string
      /** Format: uuid */
      referralId: string
      firstName?: string
      lastName?: string
      sex?: string
      crn: string
      /** Format: uuid */
      communityServiceProviderId: string
      communityServiceProviderName: string
      region: string
      referenceNumber?: string
      deliveryPartner: string
    }
    CommunitySupportServiceDto: {
      id: string
      region: string
      name: string
      providerName: string
      description: string
    }
    CommunitySupportServicesDto: {
      personId: string
      communitySupportServices: components['schemas']['CommunitySupportServiceDto'][]
    }
    ErrorResponse: {
      /**
       * Format: int32
       * @description The HTTP status code returned by the server
       * @example 404
       */
      status: number
      /**
       * Format: int32
       * @description An application-specific error code
       * @example 404
       */
      errorCode?: number
      /**
       * @description A human readable message for the error
       * @example Referral Not found
       */
      userMessage?: string
      /**
       * @description A developer friendly message for the error
       * @example null
       */
      developerMessage?: string
      /**
       * @description Additional information about the error
       * @example null
       */
      moreInfo?: string
    }
    ReferralDto: {
      /** Format: uuid */
      id: string
      crn?: string
      referenceNumber?: string
    }
    PersonAdditionalDetails: {
      ethnicity?: string
      preferredLanguage?: string
      neurodiverseConditions?: string
      religionOrBelief?: string
      transgender?: string
      sexualOrientation?: string
      address?: string
      phoneNumber?: string
      emailAddress?: string
    }
    PersonDto: {
      /** Format: uuid */
      id: string
      personIdentifier?: string
      firstName: string
      lastName: string
      /** Format: date */
      dateOfBirth: string
      sex?: string
      additionalDetails?: components['schemas']['PersonAdditionalDetails']
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  submitReferral: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SubmitReferralResponseDto']
        }
      }
    }
  }
  createReferral: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateReferralRequest']
      }
    }
    responses: {
      /** @description Referral created */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralInformationDto']
        }
      }
    }
  }
  getServices: {
    parameters: {
      query: {
        personDetailsId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description List of community support services */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CommunitySupportServicesDto']
        }
      }
      /** @description The request was unauthorised */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
      /** @description Forbidden. The client is not authorised to access to select a referral service. */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getReferral: {
    parameters: {
      query?: never
      header?: never
      path: {
        referralId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Referral found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReferralDto']
        }
      }
      /** @description Referral not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  getPersonDetails: {
    parameters: {
      query?: never
      header?: never
      path: {
        personIdentifier: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Person found */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PersonDto']
        }
      }
      /** @description Person not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
